services:
  bot:
    build: ./services/bot
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:17.5
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  db-adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  outline-server:
    image: quay.io/outline/shadowbox
    ports:
      - "40000:40000"
      - "60000:60000"
    environment:
      SB_API_PORT: 8001
      SB_API_PREFIX: /manage
      SB_CERTIFICATE_FILE: a.crt
      SB_PRIVATE_KEY_FILE: a.key

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  api:
    build: ./services/api

volumes:
  pgdata: