services:
  bot:
    build: .
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17.5
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  db-adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata: