services:
  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:17.5
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "test"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "user", "-d", "test"]
      interval: 1s
      timeout: 5s
      retries: 10

  db-adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata: